unit libData;

{$mode ObjFPC}{$H+}

interface

uses
   Classes, SysUtils;

const
   dbWindows: array[0..72] of string = (
      'PrtScn'#13#10'Print Screen'#13#10'Capture screen using Snipping Tool',
      'Del'#13#10'Delete item',
      'F1'#13#10'Help',
      'F2'#13#10'Rename the selected item',
      'F3'#13#10'Search menu/popup',
      'F4'#13#10'Activate address bar',
      'F5'#13#10'Refresh',
      'F6'#13#10'Cycle through screen elements in a window or on the desktop',
      'F10'#13#10'Activate the Menu bar',
      'Alt+Enter'#13#10'Display properties for the selected item',
      'Alt+Esc'#13#10'Cycle through items in the order in which they were opened',
      'Alt+PageDown'#13#10'Move down one screen',
      'Alt+PageUp'#13#10'Move up one screen',
      'Alt+Space'#13#10'Open system menu',
      'Alt+TAB'#13#10'Switch between open apps (next)',
      'Alt+F4'#13#10'Close window',
      'Alt+F8'#13#10'Show your password on the sign-in screen',
      'Alt+Shift+TAB'#13#10'Switch between open apps (previous)',
      'Ctrl+A'#13#10'Select All',
      'Ctrl+C'#13#10'Copy',
      'Ctrl+D'#13#10'Delete the selected item and move it to the Recycle Bin',
      'Ctrl+V'#13#10'Paste',
      'Ctrl+X'#13#10'Cut',
      'Ctrl+Y'#13#10'Redo',
      'Ctrl+Z'#13#10'Undo',
      'Ctrl+Esc'#13#10'Open Start Menu',
      'Ctrl+Ins'#13#10'Copy',
      'Ctrl+TAB'#13#10'Switch to next child window (MDI application)',
      'Ctrl+F4'#13#10'Close active child window (MDI Application)',
      'Ctrl+Alt+TAB'#13#10'Use arrow keys to switch between open windows',
      'Ctrl+Shift+N'#13#10'Create New Folder',
      'Ctrl+Shift+Esc'#13#10'Open Task Manager',
      'Shift+Del'#13#10'Delete item permanently',
      'Shift+Ins'#13#10'Paste',
      'Win'#13#10'Open Start Menu',
      'Win+1..9'#13#10'Open the 1/2..9 app pinned to the taskbar',
      'Win+A'#13#10'Open Action center',
      'Win+C'#13#10'Open Cortana/Copilot',
      'Win+D'#13#10'Toggle Show Desktop',
      'Win+E'#13#10'Open This PC',
      'Win+G'#13#10'Open Game Bar/Gadgets/Widgets',
      'Win+H'#13#10'Win 8: Open Share Charm'#13#10'Win 10+: Speech Services',
      'Win+I'#13#10'Open Settings',
      'Win+K'#13#10'Cast to...',
      'Win+L'#13#10'Lock Workstation',
      'Win+M'#13#10'Minimize all windows',
      'Win+P'#13#10'Project to...',
      'Win+R'#13#10'Open Run dialog box',
      'Win+S'#13#10'Open Search',
      'Win+T'#13#10'Cycle through apps/pinned apps on the taskbar',
      'Win+U'#13#10'Open Accessibility (Ease of Access Center)',
      'Win+X'#13#10'Open Quick Links menu',
      'Win+Down Arrow'#13#10'Minimize window',
      'Win+Home'#13#10'Toggle Minimize/Restore all but the active desktop window',
      'Win+Left Arrow'#13#10'Snap app to left of the screen',
      'Win+Pause'#13#10'Open System Properties',
      'Win+PrtScn'#13#10'Capture a screenshot and save in Screenshots folder',
      'Win+Right Arrow'#13#10'Snap app to right of the screen',
      'Win+TAB'#13#10'Open Task view',
      'Win+Up Arrow'#13#10'Maximize window',
      'Win+"+" key'#13#10'Zoom in using the magnifier',
      'Win+"," key'#13#10'Temporarily peek at the desktop',
      'Win+"-" key'#13#10'Zoom out using the magnifier',
      'Win+Ctrl+D'#13#10'Add a Virtual Desktop',
      'Win+Ctrl+Left Arrow'#13#10'Next Virtual Desktop',
      'Win+Ctrl+Right Arrow'#13#10'Previous Virtual Desktop',
      'Win+Ctrl+F4'#13#10'Close Virtual Desktop',
      'Win+Shift+M'#13#10'Restore all windows',
      'Win+Shift+Down Arrow'#13#10'Restore the stretched window to the top and bottom of the screen',
      'Win+Shift+Left Arrow'#13#10'Move window to monitor to the left',
      'Win+Shift+Right Arrow'#13#10'Move window to monitor to the right',
      'Win+Shift+Up Arrow'#13#10'Stretch window to the top and bottom of the screen',
      'Keyboard Shortcuts ScreenSaver v1.0'#13#10'©2025 Remus Rigo'
   );

   dbExcel: array[0..113] of string = (
      'Excel: Enter'#13#10'One cell down',
      'Excel: Home'#13#10'First cell in the row',
      'Excel: PageDown'#13#10'One screen Down',
      'Excel: PageUp'#13#10'One screen Up',
      'Excel: Tab'#13#10'One cell to the right',
      'Excel: F2'#13#10'Edit selected cell',
      'Excel: F3'#13#10'Displays the Paste name dialog box',
      'Excel: F4'#13#10'Repeats last action',
      'Excel: F5'#13#10'Go to a specific cell',
      'Excel: F6'#13#10'Move to the next pane',
      'Excel: F7'#13#10'Spell check selected text or document',
      'Excel: F8'#13#10'Enter Extend Mode',
      'Excel: F9'#13#10'Recalculates every workbook',
      'Excel: F11'#13#10'Creates a chart from selected data',
      'Excel: F12'#13#10'Save As',
      'Excel: Alt+Enter'#13#10'Add a new line inside a cell',
      'Excel: Alt+Backspace'#13#10'Undo',
      'Excel: Alt+"="'#13#10'Creates a formula to sum all of the above cells',
      'Excel: Alt+"''"'#13#10'Allows formatting on a dialog box',
      'Excel: Alt+F1'#13#10'Insert chart',
      'Excel: Alt+F2'#13#10'Save As',
      'Excel: Alt+F8'#13#10'Open macro dialog box',
      'Excel: Alt+F11'#13#10'Open Visual Basic editor',
      'Excel: Alt+Shift+F1'#13#10'Create a new worksheet',
      'Excel: Alt+Shift+F2'#13#10'Save the current worksheet',
      'Excel: Ctrl+0'#13#10'Hide selected/currect column',
      'Excel: Ctrl+1'#13#10'Changes the format of the selected cells',
      'Excel: Ctrl+2'#13#10'Bolds all cells in the highlighted section',
      'Excel: Ctrl+3'#13#10'Puts italics all cells in the highlighted section',
      'Excel: Ctrl+4'#13#10'Underlines all cells in highlighted section',
      'Excel: Ctrl+5'#13#10'Puts a strikethrough all cells in the highlighted section',
      'Excel: Ctrl+6'#13#10'Shows/hide objects',
      'Excel: Ctrl+7'#13#10'Show/hide the toolbar',
      'Excel: Ctrl+8'#13#10'Toggles the outline symbols',
      'Excel: Ctrl+9'#13#10'Hide selected/currect row',
      'Excel: Ctrl+B'#13#10'Bold highlighted selection/cells',
      'Excel: Ctrl+D'#13#10'Fill down (Fills the cell beneath with the contents of the selected cell)',
      'Excel: Ctrl+G'#13#10'GoTo dialog box',
      'Excel: Ctrl+H'#13#10'Find and replace dialog box',
      'Excel: Ctrl+I'#13#10'Italic highlighted selection/cells',
      'Excel: Ctrl+K'#13#10'Insert hyperlink',
      'Excel: Ctrl+N'#13#10'Opens new window with a blank document',
      'Excel: Ctrl+O'#13#10'Show Open dialog box',
      'Excel: Ctrl+P'#13#10'Show Print dialog box',
      'Excel: Ctrl+R'#13#10'Fill right (Fills the cell to the right with the contents of the selected cell)',
      'Excel: Ctrl+U'#13#10'Underline highlighted selection/cells',
      'Excel: Ctrl+W'#13#10'Close the current workbook',
      'Excel: Ctrl+Y'#13#10'Repeat last entry',
      'Excel: Ctrl+"+"'#13#10'Insert options',
      'Excel: Ctrl+"-"'#13#10'Delete options',
      'Excel: Ctrl+"["'#13#10'Selects all cells referenced by formulas in the highlighted section',
      'Excel: Ctrl+"]"'#13#10'Selects the cells that have a static value or don’t match the formula in the active cell',
      'Excel: Ctrl+;'#13#10'Insert current date',
      'Excel: Ctrl+'''#13#10'Copies a formula from the cell above',
      'Excel: Ctrl+"/"'#13#10'Selects the array containing the active cell',
      'Excel: Ctrl+"\"'#13#10'Selects the cells that have a static value or don’t match the formula in the active cell',
      'Excel: Ctrl+End'#13#10'Move to last cell in the worksheet',
      'Excel: Ctrl+Enter'#13#10'Fills the selected cells with the current entry',
      'Excel: Ctrl+Home'#13#10'Move to first cell in the worksheet',
      'Excel: Ctrl+Spacebar'#13#10'Selects the entire column',
      'Excel: Ctrl+TAB'#13#10'Switch between opened Excel worksheets (next)',
      'Excel: Ctrl+F3'#13#10'Open Excel Name Manager',
      'Excel: Ctrl+F5'#13#10'Restores window size',
      'Excel: Ctrl+F6'#13#10'Next workbook',
      'Excel: Ctrl+F7'#13#10'Move window',
      'Excel: Ctrl+F8'#13#10'Resize window',
      'Excel: Ctrl+F9'#13#10'Minimize window',
      'Excel: Ctrl+F10'#13#10'Maximize window',
      'Excel: Ctrl+F11'#13#10'Insert a macro sheet',
      'Excel: Ctrl+F12'#13#10'Open file',
      'Excel: Ctrl+Shift+1'#13#10'Applies comma formatting',
      'Excel: Ctrl+Shift+2'#13#10'Applies time formatting',
      'Excel: Ctrl+Shift+3'#13#10'Applies date formatting',
      'Excel: Ctrl+Shift+4'#13#10'Applies currency formatting',
      'Excel: Ctrl+Shift+5'#13#10'Applies percentage formatting',
      'Excel: Ctrl+Shift+6'#13#10'Applies exponential formatting',
      'Excel: Ctrl+Shift+7'#13#10'Places border around selected cells',
      'Excel: Ctrl+Shift+8'#13#10'Selects the current region around the active cell',
      'Excel: Ctrl+Shift+9'#13#10'Applies comma formatting',
      'Excel: Ctrl+Shift+"~"'#13#10'Switches between showing Excel formulas or their values in cells',
      'Excel: Ctrl+Shift+'''#13#10'Copies value from cell above',
      'Excel: Ctrl+Shift+"'#13#10'Copies value from cell above',
      'Excel: Ctrl+Shift+";"'#13#10'Insert current time',
      'Excel: Ctrl+Shift+"="'#13#10'Inserts a new column or row',
      'Excel: Ctrl+Shift+"["'#13#10'Selects all cells directly or indirectly referenced by formulas in the highlighted section',
      'Excel: Ctrl+Shift+"]"'#13#10'Selects cells which contain formulas that directly or indirectly reference the active cell',
      'Excel: Ctrl+Shift+"\"'#13#10'Selects the cells within a column that don’t match the formula or static value in the active cell',
      'Excel: Ctrl+Shift+A'#13#10'Inserts argument names into a formula',
      'Excel: Ctrl+Shift+F'#13#10'Open fonts dialog box',
      'Excel: Ctrl+Shift+O'#13#10'Selects all of the cells that contain notes',
      'Excel: Ctrl+Shift+P'#13#10'Opens the drop-down menu for point size',
      'Excel: Ctrl+Shift+Spacebar'#13#10'Selects the entire worksheet',
      'Excel: Ctrl+Shift+TAB'#13#10'Switch between previous opened Excel worksheets',
      'Excel: Ctrl+Shift+F3'#13#10'Creates names by using those of either row or column labels',
      'Excel: Ctrl+Shift+F6'#13#10'Previous workbook',
      'Excel: Ctrl+Shift+F12'#13#10'Show Print dialog box',
      'Excel: Shift+Up Arrow'#13#10'Extends the highlighted area up one cell',
      'Excel: Shift+Down Arrow'#13#10'Extends the highlighted area down one cell',
      'Excel: Shift+Left Arrow'#13#10'Extends the highlighted area Left one cell',
      'Excel: Shift+Right Arrow'#13#10'Extends the highlighted area right one cell',
      'Excel: Shift+End'#13#10'Highlights cells to the right of current cell (in a single row)',
      'Excel: Shift+Enter'#13#10'One cell up',
      'Excel: Shift+Home'#13#10'Highlights cells to the left of current cell (in a single row)',
      'Excel: Shift+Ins'#13#10'Paste from clipboard',
      'Excel: Shift+PgDn'#13#10'Highlights cells below the current cell (in a single column)',
      'Excel: Shift+PgUp'#13#10'Highlights cells above the current cell (in a single column)',
      'Excel: Shift+Tab'#13#10'One cell to the left',
      'Excel: Shift+F1'#13#10'Opens the "What''s This?" window',
      'Excel: Shift+F2'#13#10'Allows the user to edit a cell comment',
      'Excel: Shift+F3'#13#10'Open formula window',
      'Excel: Shift+F5'#13#10'Brings up a search box',
      'Excel: Shift+F6'#13#10'Move to previous pane',
      'Excel: Shift+F8'#13#10'Add to selection',
      'Excel: Shift+F9'#13#10'Performs calculate function on active sheet'
   );

   dbWord: array[0..55] of string = (
      'Word: F4'#13#10'Repeat the last action performed (Word 2000+)',
      'Word: F5'#13#10'Open GoTo dialog',
      'Word: F7'#13#10'Spellcheck and grammar check selected text or document',
      'Word: F12'#13#10'Save as dialog box',
      'Word: Ctrl+1'#13#10'Single-space lines',
      'Word: Ctrl+2'#13#10'Single-space lines',
      'Word: Ctrl+5'#13#10'1.5-line spacing',
      'Word: Ctrl+B'#13#10'Bold highlighted selection',
      'Word: Ctrl+D'#13#10'Open Font dialog',
      'Word: Ctrl+E'#13#10'Toggle Aligh selected text or line to center on/off',
      'Word: Ctrl+F'#13#10'Open Find box/Navigation',
      'Word: Ctrl+G'#13#10'Show GoTo dialog',
      'Word: Ctrl+H'#13#10'Open Find and Replace dialog',
      'Word: Ctrl+I'#13#10'Italic highlighted selection',
      'Word: Ctrl+J'#13#10'Toggle Aligh selected text or line to justify on/off',
      'Word: Ctrl+K'#13#10'Insert hyperlink',
      'Word: Ctrl+L'#13#10'Toggle Aligh selected text or line to left on/off',
      'Word: Ctrl+M'#13#10'Indent the paragraph',
      'Word: Ctrl+N'#13#10'Opens new window with a blank document',
      'Word: Ctrl+O'#13#10'Show Open dialog box',
      'Word: Ctrl+P'#13#10'Show Print dialog box',
      'Word: Ctrl+R'#13#10'Toggle Aligh selected text or line to right on/off',
      'Word: Ctrl+S'#13#10'Save document',
      'Word: Ctrl+T'#13#10'Create a hanging indent',
      'Word: Ctrl+U'#13#10'Underline the selected text',
      'Word: Ctrl+W'#13#10'Close the currently open document',
      'Word: Ctrl+]'#13#10'Increase selected font +1pts',
      'Word: Ctrl+['#13#10'Decrease selected font -1pts',
      'Word: Ctrl+Backspace'#13#10'Deletes word to left of cursor',
      'Word: Ctrl+Del'#13#10'Deletes word to right of cursor',
      'Word: Ctrl+End'#13#10'Moves the cursor to the end of the document',
      'Word: Ctrl+Home'#13#10'Moves the cursor to the beginning of the document',
      'Word: Ctrl+Left Arrow'#13#10'Move one word to the left',
      'Word: Ctrl+Right Arrow'#13#10'Move one word to the right',
      'Word: Ctrl+Spacebar'#13#10'Reset highlighted text to the default font',
      'Word: Ctrl+F1'#13#10'Show/hide ribbon menu',
      'Word: Ctrl+F2'#13#10'Print Preview',
      'Word: Ctrl+Alt+1'#13#10'Changes text to heading 1',
      'Word: Ctrl+Alt+2'#13#10'Changes text to heading 2',
      'Word: Ctrl+Alt+3'#13#10'Changes text to heading 3',
      'Word: Ctrl+Alt+F2'#13#10'Show Open dialog box',
      'Word: Ctrl+Shift+8'#13#10'View/hide non printing characters',
      'Word: Ctrl+Shift+F'#13#10'Open Font dialog',
      'Word: Ctrl+Shift+L'#13#10'Create a bullet point',
      'Word: Ctrl+Shift+T'#13#10'Turn off hanging indent',
      'Word: Ctrl+Shift+>'#13#10'Increase selected font +1pts up to 12pt and then increase font +2pts',
      'Word: Ctrl+Shift+<'#13#10'Decrease selected font -1pts if 12pt or lower; if above 12, decreases font by +2pt',
      'Word: Ctrl+Shift+F12'#13#10'Show Print dialog box',
      'Word: Shift+Enter'#13#10'Create a soft break instead of a new paragraph',
      'Word: Shift+Ins'#13#10'Paste',
      'Word: Shift+Tab'#13#10'One cell to the left',
      'Word: Shift+F3'#13#10'Switch between uppercase/lowercase/capital letter at the beginning of every line',
      'Word: Shift+F7'#13#10'Open Thesaurus check on the selected word',
      'Word: Shift+F12'#13#10'Save file dialog box',
      'Word: Shift+Alt+D'#13#10'Insert the current date',
      'Word: Shift+Alt+T'#13#10'Insert the current time'
   );

   dbBrowser: array[0..2] of string = (
      'Browser: Alt+Left arrow'#13#10'Go back',
      'Browser: Alt+Right arrow'#13#10'Go forward',
      'Browser: Ctrl-R'#13#10'Reload page'
   );

implementation

end.

